services:
  # 1. The Database
  db:
    image: postgres:15-alpine
    container_name: pdks-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourWizardPassword # Change this to your password
      POSTGRES_DB: pdks
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. The MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: pdks-broker
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  # 3. The Web API Server
  server:
    build: ./Backend/pdks-backend
    container_name: pdks-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=YourWizardPassword # Change this to your password
      - DB_NAME=pdks
      - MQTT_HOST=mosquitto
    depends_on:
      - db
      - mosquitto
    command: node server.js

  # 4. The Hardware MQTT Bridge
  collector:
    build: ./Backend/pdks-backend
    container_name: pdks-collector
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=YourWizardPassword # Change this to your password
      - DB_NAME=pdks
      - MQTT_HOST=mosquitto
    depends_on:
      - db
      - mosquitto
    command: node collector.js

volumes:
  pgdata: