; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Serial Monitor Options
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Filesystem Configuration
board_build.filesystem = littlefs

; Dependencies
lib_deps =
    ; RFID (Contains the v2 driver architecture used in your code)
    miguelbalboa/MFRC522 @ ^1.4.11
    ; W5500 Ethernet
    arduino-libraries/Ethernet @ ^2.0.2
    ; MQTT (256dpi library)
    256dpi/MQTT @ ^2.5.2
    ; JSON Parsing (v7 is strictly required for the JsonDocument syntax you used)
    bblanchon/ArduinoJson @ ^7.0.4
    ; RTC (PCF8563/DS3231 support)
    adafruit/RTClib @ ^2.1.3
    ; NTP
    arduino-libraries/NTPClient @ ^3.2.1